comment=""

[train]
model_path = "11_train_e2e_mode_{}_normalsInputFi-Fe_{}-{}-lamb0-1_{}_{}_{}_{}_{}-{}-{}-{}_cluIter_{}_bt_{}_lr_{}_knn_{}_knnStep_{}_more_{}"

knn=80
knn_step=2
Q_size = 10
num_primitives = 4
d_mean = True
d_scale = True
last = "linear" 
cluster_iterations = 5
num_points=8000
mode = 0

lamb_0_0 = 0.2
lamb_0_1 = 0.2
lamb_0_2 = 0.2
lamb_0_3 = 0.2
lamb_0_4 = 0.2
lamb_0_5 = 0.2
lamb_0_6 = 0.2
lamb_1 = 0.1

if_detection_normals = True
# [sphere, plane, cylinder, cone]
if_fitting_normals = 0,1,0,0

# Pre-trained model path
fitting_model_path = "logs/pretrained_models/quadrics_fitting/"
detection_model_path = "logs/pretrained_models/quadrics_detection/"

# Dataset path
dataset_path = "demo/demo.h5"
dataset_path_separately = "demo/"

batch_size = 12
num_epochs = 100
more = "run_pca_ABC"
# Both num and rate are acceptable, priority rate
num_train=0
num_val=0
num_test=0
# Be consistent with dection network
rate_train=0
rate_val=0
rate_test=1

lr = 0.0001