comment=""

[train]

# -------------------
Q_size = 10
num_primitives = 3
d_mean = True
d_scale = True
d_rotation = True # invalid
cluster_iterations = 5 # invalid
if_normals = False
last = "linear" 
# -------------------

model_path = "07_train_feature_mode_{}_normalsInput_{}_bt_{}_lr_{}_more_{}"

# debug
dataset_path = "data_quadrics/multShape/quadrics_100_withoutCone_normals.h5"
batch_size = 2
num_epochs = 1
more = "debug"

# # run
# dataset_path = "data_quadrics/multShape/quadrics_10000_withoutCone_normals.h5"
# batch_size = 32
# num_epochs = 100
# more = "run"

# Whether to load a pretrained model or not
preload_model = False

# 数量和比例均可，优先数量
num_train=0
num_val=0
num_test=0
rate_train=0.25
rate_val=0.05
rate_test=0.05

num_points=1000


# Optimization
optim = adam

mode = 0

lr = 0.001