comment=""

[train]

# -------------------
mode = 0
last = "linear" 
Q_size = 10
d_mean = True
d_rotation = True
d_scale = True
if_normals = True
# -------------------
test_on_another_dataset = True
dataset_dir = "data/quadrics_segments/train/"
dataset_test_dir = "data/quadrics_segments/test/"
# -------------------

model_path = "14_trans_mode_{}_numpoi_{}_normalsInput_{}_losswei_{}_{}_{}_{}_{}_{}_{}_bt_{}_lr_{}_shape_{}_more_{}"

#####run#####
# number of training instance
# num and rate are acceptable, preferred quantity
more = "run_trans_1"
num_train=0
num_val=0
num_test=0
rate_train=1
rate_val=0.2
rate_test=1
batch_size = 384
#####end#####

num_points=1100

num_epochs = 200

# Learing rate
lr = 0.001